import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {conflictReasons,validateGraph} from './work_graph.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const put=(p,x)=>{const f=path.join(root,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n');};
const hash=x=>createHash('sha256').update(x).digest('hex');
const g=read('docs/context/work-graph.json'),a=read('docs/context/source-availability.json'),policy=read('docs/context/work-orders/policy.json');
const valid=validateGraph(g);if(!valid.valid)throw Error(valid.errors.join('; '));
const byId=new Map(g.items.map(x=>[x.number,x])),phases=['prepare','candidate','accept'],num=s=>Number(String(s).replace(/^issue\./,''));
const adjacency=new Map();const edge=(x,y)=>{if(!adjacency.has(x))adjacency.set(x,new Set());adjacency.get(x).add(y)};
for(const x of g.items){edge(x.number+'@prepare',x.number+'@candidate');edge(x.number+'@candidate',x.number+'@accept');}
for(const e of g.edges.filter(x=>x.relation==='requires'))edge(num(e.to)+'@'+e.producerPhase,num(e.from)+'@'+e.consumerPhase);
const memo=new Map();const reachable=(start,target)=>{if(!memo.has(start)){const seen=new Set(),q=[start];while(q.length){const at=q.pop();for(const n of adjacency.get(at)??[])if(!seen.has(n)){seen.add(n);q.push(n)}}if(seen.has(start))throw Error('Phase cycle');memo.set(start,seen)}return memo.get(start).has(target)};
const parentOf=(x,y)=>{const seen=new Set();let at=x.parent;while(at){if(at===y.number)return true;if(seen.has(at))throw Error('Parent cycle');seen.add(at);at=byId.get(at)?.parent}return false};
const cleanTitle=x=>'['+x.workId+'] '+(policy.titleOverrides[x.number]??x.title.replace(/^\[[^\]]+\]\s*/,''));
const enrichSource=c=>{const s=a.files[c.path]??{},declared=c.availability??s.availability??'unknown',published=declared==='published'&&s.develop===true&&Boolean(s.developGitBlobSha),availability=declared==='published'&&!published?'unverified':declared;return {path:c.path,selector:c.selector,readWhen:c.readWhen,why:c.proves,limits:c.limits,availability,provider:published?'git-at-captured-ref':'qualified-source-manifest',ref:published?a.snapshot.developSHA:null,digest:published?(s.developGitBlobSha?{algorithm:'git-blob-sha1',value:s.developGitBlobSha}:null):null,url:published?'https://github.com/xrlab-dau/CHOOGuard/blob/'+a.snapshot.developSHA+'/'+c.path:null,access:published?'repository read access':'Do not read unqualified local bytes. Obtain exact path/ref/digest/access from the applicable #120 input before this consuming phase.'}};
const orders=[];const sourceNodes=new Map(),resourceNodes=new Map();
const sourceId=s=>'source:'+hash(JSON.stringify([s.path,s.ref,s.availability])).slice(0,20);
const resourceId=w=>'resource:'+hash(w.physicalBinding??w.path).slice(0,20);
for(const x of g.items){
 const predecessors=x.hardPredecessors.map(p=>({issue:p.issue,consumerPhase:p.consumerPhase,producerPhase:p.producerPhase,artifact:p.artifact}));
 const successors=x.hardSuccessors.map(p=>({issue:p.issue,consumerPhase:p.consumerPhase,producerPhase:p.producerPhase,artifact:p.artifact}));
 const conflicts=[],parallel=[];
 for(const y of g.items){if(y.number===x.number)continue;const reasons=conflictReasons(x,y,{phaseA:'accept',phaseB:'accept'});if(reasons.length)conflicts.push({issue:y.number,reasons});
 if(x.kind==='work_item'&&y.kind==='work_item'&&!reasons.length&&!parentOf(x,y)&&!parentOf(y,x)&&!reachable(x.number+'@candidate',y.number+'@candidate')&&!reachable(y.number+'@candidate',x.number+'@candidate'))parallel.push(y.number);}
 parallel.sort((u,v)=>Number(byId.get(v)?.parent===x.parent)-Number(byId.get(u)?.parent===x.parent)||Math.abs(u-x.number)-Math.abs(v-x.number)||u-v);
 const sources=x.context.map(enrichSource),firstRead=sources.filter(c=>c.availability==='published'&&(c.readWhen==='prepare'||Array.isArray(c.readWhen)&&c.readWhen.includes('prepare'))).slice(0,4);
 if(!firstRead.length)firstRead.push(...sources.filter(c=>c.availability==='published').slice(0,2));
 const outputPaths=[...new Set(x.outputs.map(o=>o.path))];
 const p={schemaVersion:1,'@context':'./ontology.jsonld','@id':'work:'+x.number,'@type':x.kind==='goal'?'Goal':'WorkItem',issue:x.number,workId:x.workId,domainCode:policy.domains[x.number]??'XR',title:cleanTitle(x),orchestrator:'role:pm',executionMode:x.kind==='goal'?'PM aggregates child deliverables; members and their LLMs execute child work.':'A member and their LLM execute this bounded task.',assignment:{policy:policy.assignment,preassigned:false,existingClaim:policy.claims[x.number]??null},environment:policy.environment,directive:policy.goalOverrides[x.number]??x.outcome,parent:x.parent??null,children:g.items.filter(y=>y.parent===x.number).map(y=>y.number),requiredOutputPaths:outputPaths,flow:{prepare:'Read this packet and only its current-phase sources. Identify missing inputs, plan exact changes and tests. Do not claim another member’s work.',candidate:'After candidate-phase inputs are qualified, claim exact paths/branch and perform the implementation or verification requested here.',accept:'Run every required check, preserve failed/unrun cases, return evidence. PM evaluates handoff; a document or checkbox alone is not completion.'},relations:{predecessors,successors,oneOfGroups:x.oneOfInputs.map(q=>({artifact:q.artifact,consumerPhase:q.consumerPhase,resolution:q.resolution,alternatives:q.alternatives.map(z=>({issue:z.issue,artifact:z.artifact,producerPhase:z.producerPhase}))})),parallelCandidates:parallel,parallelCondition:'Candidate-phase plan only. Required inputs must be available, actual branches/checkouts and mutable resources must be separate, and exact write claims must not overlap. This is not a live lease or an assignment.',conflicts:conflicts.map(z=>({issue:z.issue,reasons:z.reasons}))},minimumContext:firstRead,readMore:{sources:'node scripts/context/task_context.mjs brief --issue '+x.number+' --section sources --phase prepare',inputs:'node scripts/context/task_context.mjs brief --issue '+x.number+' --section inputs --phase candidate',writes:'node scripts/context/task_context.mjs brief --issue '+x.number+' --section writes --phase candidate',checks:'node scripts/context/task_context.mjs brief --issue '+x.number+' --section checks --phase candidate',history:'node scripts/context/task_context.mjs brief --issue '+x.number+' --section history'},handoff:['workId and phase','branch/commit and changed paths','input and output refs/digests','checks actually run and their result','failed/unrun items and current blockers','successor handoff and claim release'],technicalContract:{path:'docs/context/work-graph.json',selector:'items[number='+x.number+']',scope:'Exact phase inputs, artifact qualifications, write/resource contracts, checks and evidence. Historical capture/review fields are not current assignments or a mandatory review loop.'},sourceSnapshot:{capturedAt:g.snapshot.capturedAt,liveState:'Read GitHub Project at actual start; this packet grants no live lease or blanket external-action permission.'}};
 orders.push(p);put('docs/context/work-orders/'+String(x.number).padStart(3,'0')+'.json',p);
 for(const s of sources){const id=sourceId(s);sourceNodes.set(id,{'@id':id,'@type':'Source',path:s.path,provider:s.provider,ref:s.ref,digest:s.digest,availability:s.availability,access:s.access});}
 for(const phase of phases)for(const w of x.phaseWriteScopes[phase]??[]){const id=resourceId(w);resourceNodes.set(id,{'@id':id,'@type':'Resource',path:w.path,physicalBinding:w.physicalBinding,allocation:'bound only at actual claim; no machine/person preassignment'});}
}
const ontology={'@context':{'@vocab':'https://github.com/xrlab-dau/CHOOGuard#',domain:'https://github.com/xrlab-dau/CHOOGuard#domain/',classifiedAs:{'@id':'cg:classifiedAs','@type':'@id'},requirement:'https://github.com/xrlab-dau/CHOOGuard#requirement/',usesSource:{'@id':'cg:usesSource','@type':'@id'},resources:{'@id':'cg:resources','@type':'@id'},requiresOneOf:{'@id':'cg:requiresOneOf','@type':'@id'},from:{'@id':'cg:from','@type':'@id'},to:{'@id':'cg:to','@type':'@id'},cg:'https://github.com/xrlab-dau/CHOOGuard#',work:'https://github.com/xrlab-dau/CHOOGuard#work/',phase:'https://github.com/xrlab-dau/CHOOGuard#phase/',artifact:'https://github.com/xrlab-dau/CHOOGuard#artifact/',source:'https://github.com/xrlab-dau/CHOOGuard#source/',resource:'https://github.com/xrlab-dau/CHOOGuard#resource/',role:'https://github.com/xrlab-dau/CHOOGuard#role/',Goal:'cg:Goal',WorkItem:'cg:WorkItem',WorkPhase:'cg:WorkPhase',Artifact:'cg:Artifact',Source:'cg:Source',Resource:'cg:Resource',Role:'cg:Role',Dependency:'cg:Dependency',partOf:{'@id':'cg:partOf','@type':'@id'},orchestrator:{'@id':'cg:orchestrator','@type':'@id'},producer:{'@id':'cg:producer','@type':'@id'},consumer:{'@id':'cg:consumer','@type':'@id'},usesArtifact:{'@id':'cg:usesArtifact','@type':'@id'},produces:{'@id':'cg:produces','@type':'@id'},parallelWith:{'@id':'cg:parallelWith','@type':'@id'},conflictsWith:{'@id':'cg:conflictsWith','@type':'@id'}},meaning:'Project-specific LLM-readable ontology, not a claimed universal LLM standard. Dependencies bind producer/consumer phases and artifact identity; contains/partOf is not execution order.'};put('docs/context/work-orders/ontology.jsonld',ontology);
const graph=[{'@id':'role:pm','@type':'Role',label:'PM issues work, selects priorities and resolves decisions; no executor preassignment.'},{'@id':'role:executor','@type':'Role',label:'A member with their LLM; actual owner is recorded only at claim.'}];
for(const code of ['PM','XR','MAP','UX','QA'])graph.push({'@id':'domain:'+code,'@type':'Domain',code,meaning:'functional classification, not a member assignment'});
for(const p of orders){const x=byId.get(p.issue);graph.push({'@id':p['@id'],'@type':p['@type'],workId:p.workId,title:p.title,classifiedAs:'domain:'+p.domainCode,packet:String(p.issue).padStart(3,'0')+'.json',orchestrator:'role:pm',...(p.parent?{partOf:'work:'+p.parent}:{}),parallelWith:p.relations.parallelCandidates.map(n=>'work:'+n),conflictsWith:p.relations.conflicts.map(z=>'work:'+z.issue),contextSelections:x.context.map(c=>{const s=enrichSource(c);return {usesSource:sourceId(s),selector:s.selector,readWhen:s.readWhen,why:s.why,limits:s.limits}})});for(const phase of phases)graph.push({'@id':'phase:'+p.issue+'/'+phase,'@type':'WorkPhase',partOf:p['@id'],phase,produces:x.outputs.filter(o=>o.producerPhase===phase).map(o=>o.id),resources:(x.phaseWriteScopes[phase]??[]).map(resourceId),requiresOneOf:x.oneOfInputs.filter(o=>o.consumerPhase===phase).map(o=>o.artifact)});}
for(const x of g.items)for(const o of x.outputs)graph.push({'@id':o.id,'@type':'Artifact',producer:'phase:'+x.number+'/'+o.producerPhase,path:o.path,qualification:o.qualification,digestRequirements:o.digestRequirements});
let count=0;for(const e of g.edges.filter(x=>x.relation==='requires'))graph.push({'@id':'cg:dependency/'+(++count),'@type':'Dependency',producer:'phase:'+num(e.to)+'/'+e.producerPhase,consumer:'phase:'+num(e.from)+'/'+e.consumerPhase,usesArtifact:e.artifact,reason:e.reason});
for(const r of g.references){graph.push({'@id':'work:'+r.number,'@type':'HistoricalReference',title:r.title,state:r.state,limits:r.limits});for(const o of r.outputs??[])graph.push({'@id':o.id,'@type':'HistoricalArtifact',producer:'work:'+r.number,...o,historicalOnly:true});}
for(const x of g.items)for(const group of x.oneOfInputs){graph.push({'@id':group.artifact,'@type':'ConditionalArtifact',consumer:'phase:'+x.number+'/'+group.consumerPhase,resolution:group.resolution,alternatives:group.alternatives.map(z=>({...z,producer:'phase:'+z.issue+'/'+z.producerPhase,usesArtifact:z.artifact}))});for(const z of group.alternatives)if(!byId.has(z.issue)&&!graph.some(n=>n['@id']==='phase:'+z.issue+'/'+z.producerPhase))graph.push({'@id':'phase:'+z.issue+'/'+z.producerPhase,'@type':'HistoricalPhase',partOf:'work:'+z.issue,phase:z.producerPhase,historicalOnly:true});}
const ids=new Map(g.requirements.map(r=>[r.id,'requirement:'+r.id]));for(const r of g.requirements)graph.push({'@id':ids.get(r.id),'@type':'Requirement',code:r.code,title:r.title,limits:r.limits});
const iri=s=>/^issue\.\d+$/.test(s)?'work:'+num(s):(ids.get(s)??s);
let rel=0;for(const e of g.edges.filter(e=>!['requires','contains'].includes(e.relation)))graph.push({'@id':'cg:relation/'+(++rel),'@type':'Relationship',relation:e.relation,from:iri(e.from),to:iri(e.to),reason:e.reason??null});
graph.push(...sourceNodes.values(),...resourceNodes.values());put('docs/context/work-orders/index.jsonld',{'@context':'./ontology.jsonld',scope:'101 open work instructions; phase-specific dependency ontology; not acceptance or live ownership','@graph':graph});
put('docs/context/work-orders/README.md','# LLM 작업 문맥 레지스트리\n\n현재 지시: [PM 오케스트레이션 계약](../orchestration-contract.md). 이 레지스트리는 계획·지시·실제 실행·증거를 구별합니다.\n\n- `NNN.json`: 해당 이슈의 실행 지시와 최소 문맥\n- `ontology.jsonld`: 프로젝트 온톨로지와 관계 방향\n- `index.jsonld`: Goal/WorkItem/Phase/Artifact/Source/Resource/Role 등록\n- 상세 입력·쓰기·검증은 `task_context.mjs --section`으로 해당 이슈/단계만 읽습니다.\n\n| 이슈 | PM 작업 지시 | 문맥 |\n|---|---|---|\n'+orders.map(p=>`| [#${p.issue}](https://github.com/xrlab-dau/CHOOGuard/issues/${p.issue}) | ${p.title} | [packet](${String(p.issue).padStart(3,'0')}.json) |`).join('\n')+'\n');
console.log(JSON.stringify({workOrders:orders.length,phaseDependencies:count,artifacts:g.items.reduce((s,x)=>s+x.outputs.length,0),sources:sourceNodes.size,resources:resourceNodes.size,parallelDirected:orders.reduce((s,x)=>s+x.relations.parallelCandidates.length,0),conflictDirected:orders.reduce((s,x)=>s+x.relations.conflicts.length,0)},null,2));
