if(UnityEditor.EditorApplication.isPlaying||UnityEditor.EditorApplication.isCompiling||UnityEditor.EditorApplication.isUpdating)throw new System.Exception("Edit ready required");
var world=UnityEngine.GameObject.Find("FPSWorld");var ktx=world.transform.Find("KTXSource");string patchName="Coach02InnerDoorStaticOpenPatch";if(ktx.Find(patchName)!=null)throw new System.Exception("Patch already present; inspect before retry");
var names=new[]{"Car02_T2 2car_08_T2-1_in_001","Car02_T2 2car_08_T2-1_in_004","Car02_T2 2car_08_T2-1_in_005"};var originals=new System.Collections.Generic.List<UnityEngine.GameObject>();int oldTriangles=0;
foreach(var name in names){var found=ktx.Find(name);if(found==null||!found.gameObject.activeSelf||found.GetComponent<UnityEngine.MeshCollider>()==null)throw new System.Exception("Exact original mesh dependency missing "+name);originals.Add(found.gameObject);oldTriangles+=found.GetComponent<UnityEngine.MeshFilter>().sharedMesh.triangles.Length/3;}
var asset=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.GameObject>("Assets/ChooGuard/Art/Fps/KTXCoach02DoorPatch/coach2-inner-door-static-patch.fbx");if(asset==null)throw new System.Exception("Import required");UnityEngine.GameObject clone=null;
try{
clone=UnityEngine.Object.Instantiate(asset);clone.name=patchName;var filters=clone.GetComponentsInChildren<UnityEngine.MeshFilter>();if(filters.Length!=6)throw new System.Exception("Expected six replacement meshes");var got=new System.Collections.Generic.HashSet<string>();int newTriangles=0;foreach(var filter in filters){got.Add(filter.name);newTriangles+=filter.sharedMesh.triangles.Length/3;if(filter.GetComponent<UnityEngine.MeshRenderer>().sharedMaterials.Length!=1)throw new System.Exception("Single source material per block required");}
foreach(var block in new[]{"001","004","005"})foreach(var part in new[]{"Fixed","Leaf"})if(!got.Contains("Coach02_Inner"+part+"_Block"+block))throw new System.Exception("Replacement name mismatch");if(oldTriangles!=newTriangles)throw new System.Exception("Original/replacement triangle accounting differs "+oldTriangles+" vs "+newTriangles);
var renderers=clone.GetComponentsInChildren<UnityEngine.Renderer>();var canonicalBounds=renderers[0].bounds;foreach(var r in renderers)canonicalBounds.Encapsulate(r.bounds);if(canonicalBounds.size.z<15||canonicalBounds.size.z>25||canonicalBounds.size.x<2||canonicalBounds.size.x>4||canonicalBounds.center.z<30||canonicalBounds.center.z>55)throw new System.Exception("Fulltrain canonicalpatchbounds mismatch "+canonicalBounds);
var rotation=UnityEngine.Quaternion.Euler(0,200.3248713f,0);clone.transform.SetParent(world.transform,false);clone.transform.localPosition=new UnityEngine.Vector3(88.9187956f,-.73000026f,76.4428219f)+rotation*asset.transform.localPosition;clone.transform.localRotation=rotation*asset.transform.localRotation;clone.transform.localScale=asset.transform.localScale;clone.transform.SetParent(ktx,true);
foreach(var filter in filters){var collider=filter.gameObject.AddComponent<UnityEngine.MeshCollider>();collider.sharedMesh=filter.sharedMesh;collider.convex=false;}
foreach(var original in originals)original.SetActive(false);UnityEngine.Physics.SyncTransforms();var depth=ChooGuard.Editor.KtxOpaqueTexelDepthSupport.Repair(".planning/2026-09-21-fps-reposition/bve-import/ktx-material-manifest.normalized.json");
UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(world.scene);if(!UnityEditor.SceneManagement.EditorSceneManager.SaveScene(world.scene))throw new System.Exception("Save failed");int activeColliders=0;foreach(var c in world.GetComponentsInChildren<UnityEngine.Collider>(false))if(c.enabled)activeColliders++;
return new{status="EXACT_COACH02_INNER_LEAF_STATIC_OPEN_PATCH_APPLIED",originalsDeactivated=names,oldTriangles,newTriangles,replacementMeshes=filters.Length,patchCanonicalBounds=canonicalBounds.ToString(),activeColliders,depthRepair=depth,limits="Authoredstatic+.88mBVE_X pose of276trueleaf faces; sourcefixedbody/frame/UV retained; no actualdooranimation/pocketkinematicsclaim"};
}catch{foreach(var original in originals)if(original!=null)original.SetActive(true);if(clone!=null)UnityEngine.Object.DestroyImmediate(clone);UnityEngine.Physics.SyncTransforms();throw;}
