var rows=new System.Collections.Generic.List<object>();
foreach(var path in new[]{"Assets/ChooGuard/Art/Fps/KTX/ktx-single-10car-left-open.fbx","Assets/ChooGuard/Art/Fps/Metro113/Busan113FPSSection.fbx"}){
var a=UnityEditor.AssetDatabase.LoadAssetAtPath<UnityEngine.GameObject>(path);if(a==null)throw new System.Exception("Imported model missing");
var filters=a.GetComponentsInChildren<UnityEngine.MeshFilter>(true);bool first=true;var bounds=new UnityEngine.Bounds();var paths=new System.Collections.Generic.List<string>();
foreach(var f in filters){var relative=f.name;var parent=f.transform.parent;while(parent!=a.transform&&parent!=null){relative=parent.name+"/"+relative;parent=parent.parent;}paths.Add(relative);foreach(var v in f.sharedMesh.vertices){var p=f.transform.TransformPoint(v);if(first){bounds=new UnityEngine.Bounds(p,UnityEngine.Vector3.zero);first=false;}else bounds.Encapsulate(p);}}
var mats=System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Distinct(System.Linq.Enumerable.SelectMany(a.GetComponentsInChildren<UnityEngine.Renderer>(true),r=>r.sharedMaterials)));
rows.Add(new{path,meshes=filters.Length,vertices=System.Linq.Enumerable.Sum(filters,f=>f.sharedMesh.vertexCount),triangles=System.Linq.Enumerable.Sum(filters,f=>f.sharedMesh.triangles.Length/3),min=new{x=bounds.min.x,y=bounds.min.y,z=bounds.min.z},max=new{x=bounds.max.x,y=bounds.max.y,z=bounds.max.z},materials=mats.Length,textured=System.Linq.Enumerable.Count(mats,m=>m!=null&&m.mainTexture!=null),unmapped=System.Linq.Enumerable.Count(mats,m=>m==null||!UnityEditor.AssetDatabase.GetAssetPath(m).Contains("/Materials/")),meshPaths=paths});}
var w=UnityEngine.Object.FindFirstObjectByType<ChooGuard.App.Mvp.MvpWorkspace>();
return new{models=rows,font=UnityEditor.AssetDatabase.GetAssetPath(w.Font),sourceScene=UnityEngine.SceneManagement.SceneManager.GetActiveScene().name,sourceDirty=UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty,compiling=UnityEditor.EditorApplication.isCompiling};
