if(!UnityEditor.EditorApplication.isPlaying)throw new System.Exception("Play required");
var p=UnityEngine.Object.FindFirstObjectByType<ChooGuard.App.Fps.FirstPersonResponder>();
var c=p.GetComponent<UnityEngine.CharacterController>();p.SetExternalInputMode(true);p.Resume(false);
var goals=new[]{new UnityEngine.Vector3(-162.0221f,-8,61.2617f),new UnityEngine.Vector3(-169.5207f,-3.5f,44.8979f),new UnityEngine.Vector3(-175.7696f,-3.5f,31.2615f),new UnityEngine.Vector3(-170.9408f,-3.5f,-24.587f),new UnityEngine.Vector3(-176.7731f,0,-37.3143f),new UnityEngine.Vector3(-169.5003f,.145004f,-40.647f)};
var rows=new System.Collections.Generic.List<object>();int total=0;bool all=true;
foreach(var goal in goals){int steps=0,stuck=0;bool reached=false;var previous=p.transform.position;
for(;steps<2000;steps++){var delta=goal-p.transform.position;var flat=new UnityEngine.Vector2(delta.x,delta.z);if(flat.magnitude<.18f){reached=UnityEngine.Mathf.Abs(p.transform.position.y-goal.y)<.35f;break;}float yaw=UnityEngine.Mathf.Atan2(delta.x,delta.z)*UnityEngine.Mathf.Rad2Deg;float turn=UnityEngine.Mathf.DeltaAngle(p.YawDegrees,yaw);bool move=UnityEngine.Mathf.Abs(turn)<10;p.StepInput(move?UnityEngine.Vector2.up:UnityEngine.Vector2.zero,new UnityEngine.Vector2(turn,0),false,false,false,.05f);total++;var now=p.transform.position;if(move&&UnityEngine.Vector2.Distance(new UnityEngine.Vector2(now.x,now.z),new UnityEngine.Vector2(previous.x,previous.z))<.002f)stuck++;else stuck=0;previous=now;if(stuck>60||now.y< -15||p.IsPaused)break;}
var pos=p.transform.position;rows.Add(new{goal=new{x=goal.x,y=goal.y,z=goal.z},reached,steps,stuck,position=new{x=pos.x,y=pos.y,z=pos.z},grounded=c.isGrounded,flags=p.LastCollisionFlags.ToString()});if(!reached){all=false;break;}}
p.Pause();return new{status=all?"PASS":"FAIL",scope="Native CharacterController via public StepInput .05s; continuous Metro-to-spawn reverse path, no teleport and no OSinput claim",acceptedSimSeconds=total*.05f,checkpoints=rows};
