#!/usr/bin/env python3
"""Out-of-editor execution driver for the FMP-11c (issue #139) test file.

WHAT THIS IS
  Compiles Packages/com.xrlab.chooguard.foundation/Multiplayer/Tests/Editor/FMP11cObservedRouteConsistencyTests.cs
  against the real Runtime sources using the Roslyn compiler and the .NET runtime that ship inside
  the Unity editor install, then runs the [Test] methods with a console runner and a local
  NUnit-shaped assertion shim.

WHAT THIS IS NOT
  This is NOT NUnit and NOT the Unity Test Runner. There is no [OneTimeSetUp]/[SetUp] lifecycle
  beyond the minimal shim, no Unity editor environment, no test categories, no NUnit3 XML, no
  asset import, no scene, no PlayMode. A pass here shows the assertions hold against the real
  Runtime sources; it does NOT show that the same tests pass inside the editor.

WHY TWO FILES ARE EXTRACTED BY LINE RANGE
  Multiplayer/Runtime/NetworkFieldRuntime.cs and Multiplayer/Runtime/ConnectedWorldRuntime.cs are
  MonoBehaviours that reference Unity.Netcode / Unity.Collections / UnityEngine. No assembly for
  those packages exists outside the Unity project Library, so the two projection methods under
  test are copied out verbatim by line range (see EXTRACTION_MANIFEST below and each block's
  sha256 in the run record). The copy is exact; if it ever diverges from production the recorded
  block digests stop matching.

USAGE
  CG_UNITY_SCRIPTING=<.../Unity.app/Contents/Resources/Scripting> \
  CG_WORK=<scratch dir> \
  python3 out_of_editor_run.py [--baseline-only] [--case <ID> ...] [--out <dir>]
"""
import argparse
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
WT = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..", ".."))
U = os.environ.get("CG_UNITY_SCRIPTING",
                   "/Applications/Unity/Unity-6000.3.23f1/Unity.app/Contents/Resources/Scripting")
DOTNET = os.path.join(U, "NetCoreRuntime", "dotnet")
RT = os.path.join(U, "NetCoreRuntime", "shared", "Microsoft.NETCore.App", "6.0.21")
CSC = os.path.join(U, "DotNetSdkRoslyn", "csc.dll")

FND = os.path.join(WT, "Packages", "com.xrlab.chooguard.foundation")
RUNTIME_SRC = os.path.join(FND, "Runtime")
NFR = os.path.join(FND, "Multiplayer", "Runtime", "NetworkFieldRuntime.cs")
CWR = os.path.join(FND, "Multiplayer", "Runtime", "ConnectedWorldRuntime.cs")
FRESHNESS = os.path.join(FND, "Multiplayer", "Runtime", "SnapshotFreshness.cs")
PHYSICAL = os.path.join(FND, "Multiplayer", "Runtime", "WorldPhysicalView.cs")
TESTS = os.path.join(FND, "Multiplayer", "Tests", "Editor", "FMP11cObservedRouteConsistencyTests.cs")
PROFILE = os.path.join(WT, "foundation", "world", "connected-world-profile.json")
NOWARN = "0162,0219,0414,0649,1701,1702,8321,8632"

# Verbatim line ranges copied out of the two Unity-dependent projection files.
NFR_POCO_BLOCKS = [(22, 77)]
NFR_METHOD_BLOCKS = [(971, 971), (973, 974), (990, 1074), (1079, 1114)]
CWR_BLOCKS = [(155, 163)]

EXTRACTION_MANIFEST = []
WORK = None


def lines_of(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read().split("\n")


def block_text(path, ranges):
    src = lines_of(path)
    out = []
    for (a, b) in ranges:
        text = "\n".join(src[a - 1:b])
        out.append(text)
        EXTRACTION_MANIFEST.append({"file": os.path.relpath(path, WT), "lines": "%d-%d" % (a, b),
                                    "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest()})
    return "\n".join(out)


def write_extracted(path):
    header = ("// GENERATED by out_of_editor_run.py: verbatim line-range copies of production sources.\n"
              "// Do not edit. Each block's source file and line range is recorded in the run record\n"
              "// together with its sha256.\n")
    body = ("using System;\nusing System.Collections.Generic;\nusing System.Linq;\n"
            "using ChooGuard.Foundation.Simulation;\n\nnamespace ChooGuard.Foundation.Multiplayer\n{\n")
    body += block_text(NFR, NFR_POCO_BLOCKS) + "\n\n"
    body += "    public sealed class NetworkFieldRuntime\n    {\n"
    body += block_text(NFR, NFR_METHOD_BLOCKS) + "\n    }\n\n"
    body += "    public sealed class ConnectedWorldRuntime\n    {\n"
    body += block_text(CWR, CWR_BLOCKS) + "\n    }\n"
    body += "}\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(header + body)


def fresh_tree():
    src_dir = os.path.join(WORK, "src")
    del EXTRACTION_MANIFEST[:]
    if os.path.isdir(WORK):
        shutil.rmtree(WORK)
    os.makedirs(src_dir)
    subprocess.run(["cp", "-R", RUNTIME_SRC + "/.", src_dir + "/"], check=True)
    shutil.copy(FRESHNESS, os.path.join(src_dir, "_SnapshotFreshness.cs"))
    shutil.copy(PHYSICAL, os.path.join(src_dir, "_WorldPhysicalView.cs"))
    write_extracted(os.path.join(src_dir, "_ExtractedProjections.cs"))
    os.makedirs(os.path.join(WORK, "foundation", "world"))
    shutil.copy(PROFILE, os.path.join(WORK, "foundation", "world", "connected-world-profile.json"))


def apply_mutation(src_dir, mutation):
    for rep in mutation["replacements"]:
        hits = 0
        for root, _dirs, files in os.walk(src_dir):
            for f in files:
                if not f.endswith(".cs"):
                    continue
                p = os.path.join(root, f)
                with open(p, encoding="utf-8") as fh:
                    text = fh.read()
                n = text.count(rep["old"])
                if n:
                    if n != 1:
                        return "PROBE ERROR: anchor occurs %d times in %s" % (n, f)
                    with open(p, "w", encoding="utf-8") as fh:
                        fh.write(text.replace(rep["old"], rep["new"]))
                    hits += n
        if hits != 1:
            return "PROBE ERROR: anchor not found (hits=%d)" % hits
    return None


def build_rsp(dll_out, rsp_path):
    lines = ["-nologo", "-nostdlib", "-target:exe", "-langversion:latest", "-warn:0",
             "-nowarn:" + NOWARN, "-out:" + dll_out]
    for f in sorted(os.listdir(RT)):
        if f.endswith(".dll"):
            lines.append("-r:" + RT + "/" + f)
    for root, _dirs, files in os.walk(os.path.join(WORK, "src")):
        for f in sorted(files):
            if f.endswith(".cs"):
                lines.append(os.path.join(root, f))
    for extra in ("NUnitShim.cs", "UnityShim.cs", "Runner.cs"):
        lines.append(os.path.join(HERE, extra))
    lines.append(TESTS)
    with open(rsp_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def run_case(case_id, mutations, log_fh):
    import re
    t0 = time.time()
    fresh_tree()
    src_dir = os.path.join(WORK, "src")
    note = "baseline (no mutation)"
    if mutations:
        for m in mutations:
            err = apply_mutation(src_dir, m)
            if err:
                log_fh.write("\n===== CASE %s =====\n%s\n" % (case_id, err))
                return {"id": case_id, "status": "probe_error", "error": err}
        note = mutations[0]["note"]

    dll = os.path.join(WORK, "harness.dll")
    rsp = os.path.join(WORK, "build.rsp")
    build_rsp(dll, rsp)
    cp = subprocess.run([DOTNET, "exec", CSC, "@" + rsp], capture_output=True, text=True)
    compile_out = (cp.stdout or "") + (cp.stderr or "")
    errors = [l for l in compile_out.splitlines() if " error CS" in l]
    if cp.returncode != 0 or errors:
        log_fh.write("\n===== CASE %s (%s) =====\nBUILD FAILED rc=%d\n%s\n" % (case_id, note, cp.returncode, compile_out))
        return {"id": case_id, "status": "build_failed", "compileOutput": compile_out[:4000]}

    shutil.copy(os.path.join(HERE, "harness.runtimeconfig.json"), os.path.join(WORK, "harness.runtimeconfig.json"))
    rp = subprocess.run([DOTNET, "exec", dll], capture_output=True, text=True, cwd=WORK)
    out = (rp.stdout or "") + (rp.stderr or "")
    fails = re.findall(r"^FAIL\s+(\S+)", out, re.M)
    errors2 = re.findall(r"^ERROR\s+(\S+)", out, re.M)
    passes = re.findall(r"^PASS\s+(\S+)", out, re.M)
    total = len(fails) + len(passes) + len(errors2)
    log_fh.write("\n===== CASE %s (%s) =====\ncompile: rc=%d\n" % (case_id, note, cp.returncode))
    log_fh.write(out if out.endswith("\n") else out + "\n")
    log_fh.flush()
    if total == 0:
        return {"id": case_id, "status": "no_tests", "rawOutput": out[:4000]}
    return {"id": case_id, "status": "caught" if (fails or errors2) else "survived", "mutation": note,
            "testsRun": total, "passed": len(passes), "failedCount": len(fails) + len(errors2),
            "caughtBy": fails + errors2, "elapsedSeconds": round(time.time() - t0, 1)}


def sha256_of(path):
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def main():
    global WORK
    parser = argparse.ArgumentParser()
    parser.add_argument("--baseline-only", action="store_true")
    parser.add_argument("--case", action="append", default=[])
    parser.add_argument("--out", default=HERE)
    args = parser.parse_args()
    os.makedirs(args.out, exist_ok=True)
    WORK = os.environ.get("CG_WORK") or tempfile.mkdtemp(prefix="fmp11c-out-of-editor-")

    for required in (DOTNET, CSC, RT):
        if not os.path.exists(required):
            print("missing Unity-bundled toolchain: " + required)
            return 3

    spec = json.load(open(os.path.join(HERE, "mutation-spec.json"), encoding="utf-8"))
    log_path = os.path.join(args.out, "harness-raw-output.txt")
    results = []
    with open(log_path, "w", encoding="utf-8") as log_fh:
        log_fh.write("FMP-11c (issue #139) out-of-editor harness raw output\n")
        log_fh.write("compiler: %s\n" % CSC)
        log_fh.write("runtime:  %s\n" % RT)
        log_fh.write("worktree: %s\n" % WT)
        log_fh.write("testfile: %s\n" % os.path.relpath(TESTS, WT))
        log_fh.write("testfile sha256: %s\n" % sha256_of(TESTS))
        log_fh.write("note: NOT the Unity test runner and NOT NUnit; console runner + local shim.\n")
        log_fh.flush()
        results.append(run_case("baseline-unmutated", [], log_fh))
        if not args.baseline_only:
            for m in spec["mutations"]:
                if args.case and m["id"] not in args.case:
                    continue
                results.append(run_case(m["id"], [m], log_fh))

    record = {
        "recordKind": "out_of_editor_run_record",
        "harnessIsNot": "Not NUnit and not the Unity Test Runner: Unity-bundled Roslyn csc.dll + .NET runtime "
                        "+ local NUnit-shaped shim + console runner. Cannot show [OneTimeSetUp]/[SetUp] lifecycle, "
                        "the editor environment, test categories, NUnit3 XML, asset import or PlayMode.",
        "testFile": os.path.relpath(TESTS, WT),
        "testFileSha256": sha256_of(TESTS),
        "collectionRoot": WT,
        "platform": {"sysPlatform": sys.platform, "machine": platform.machine(),
                     "dotnetRuntime": "6.0.21", "compiler": "Unity-bundled Roslyn csc.dll"},
        "extractionManifest": EXTRACTION_MANIFEST,
        "results": results,
    }
    with open(os.path.join(args.out, "run-record.json"), "w", encoding="utf-8") as fh:
        json.dump(record, fh, ensure_ascii=False, indent=2)
    caught = sum(1 for r in results if r["status"] == "caught")
    survived = [r["id"] for r in results if r["status"] == "survived"]
    print("cases=%d caught=%d survived=%s" % (len(results), caught, survived))
    print("wrote %s" % os.path.join(args.out, "run-record.json"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
