-- Design DDL. Tested with local SQLite fixture only; production binding is separate.
PRAGMA foreign_keys=ON;
CREATE TABLE project(project_id TEXT PRIMARY KEY, schema_version INTEGER NOT NULL);
CREATE TABLE artifact(hash TEXT PRIMARY KEY CHECK(length(hash)=64), bytes INTEGER NOT NULL CHECK(bytes>=0), media_type TEXT NOT NULL, blob_path TEXT NOT NULL);
CREATE TABLE content_revision(revision_id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(project_id), kind TEXT NOT NULL, content_hash TEXT NOT NULL REFERENCES artifact(hash));
CREATE TABLE run(run_id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(project_id), parent_run_id TEXT REFERENCES run(run_id), parent_sequence INTEGER, input_hash TEXT NOT NULL, mode TEXT NOT NULL CHECK(mode IN ('TUTORIAL','RANDOM_OPERATIONS_LAB')), epoch INTEGER NOT NULL DEFAULT 1, last_sequence INTEGER NOT NULL DEFAULT 0);
CREATE TABLE ledger(run_id TEXT NOT NULL REFERENCES run(run_id), sequence INTEGER NOT NULL CHECK(sequence>0), event_id TEXT NOT NULL, simulation_ticks TEXT NOT NULL, kind TEXT NOT NULL, payload_hash TEXT NOT NULL, event_hash TEXT NOT NULL, PRIMARY KEY(run_id,sequence), UNIQUE(run_id,event_id));
CREATE TABLE receipt(run_id TEXT NOT NULL REFERENCES run(run_id), requester_id TEXT NOT NULL, intent_id TEXT NOT NULL, fingerprint TEXT NOT NULL, decision TEXT NOT NULL CHECK(decision IN ('ACCEPTED','REJECTED')), committed_sequence INTEGER, payload_json TEXT NOT NULL, PRIMARY KEY(run_id,requester_id,intent_id), CHECK(decision!='ACCEPTED' OR (committed_sequence IS NOT NULL AND committed_sequence>0)));
CREATE TABLE resource_hold(run_id TEXT NOT NULL REFERENCES run(run_id), resource_id TEXT NOT NULL, task_id TEXT NOT NULL, PRIMARY KEY(run_id,resource_id));
CREATE TABLE outbox(outbox_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES run(run_id), caused_by_sequence INTEGER NOT NULL, job_id TEXT NOT NULL, input_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('PENDING','SENT','ACKED','FAILED')));
CREATE TABLE worker_result(result_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES run(run_id), job_id TEXT NOT NULL, worker_id TEXT NOT NULL, worker_epoch INTEGER NOT NULL, input_hash TEXT NOT NULL, boundary_revision INTEGER NOT NULL, artifact_hash TEXT NOT NULL REFERENCES artifact(hash), applied_sequence INTEGER, UNIQUE(run_id,job_id,worker_epoch,input_hash));
CREATE TABLE checkpoint(checkpoint_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES run(run_id), sequence INTEGER NOT NULL, manifest_hash TEXT NOT NULL REFERENCES artifact(hash), completeness TEXT NOT NULL CHECK(completeness IN ('PREPARING','COMPLETE','INCOMPLETE')));
CREATE TABLE checkpoint_worker(checkpoint_id TEXT NOT NULL REFERENCES checkpoint(checkpoint_id), worker_id TEXT NOT NULL, state_hash TEXT NOT NULL REFERENCES artifact(hash), restart_policy TEXT NOT NULL, PRIMARY KEY(checkpoint_id,worker_id));
CREATE TABLE qualification(qualification_id TEXT PRIMARY KEY, subject_hash TEXT NOT NULL, facet TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('NOT_EVALUATED','REJECTED','PASSED_WITH_SCOPE','STALE','REVOKED')), scope_id TEXT NOT NULL, evidence_json TEXT NOT NULL, reviewer_id TEXT);
CREATE TABLE script_revision(script_revision_id TEXT PRIMARY KEY, plan_revision_id TEXT NOT NULL REFERENCES content_revision(revision_id), representative_run_id TEXT NOT NULL REFERENCES run(run_id), script_hash TEXT NOT NULL REFERENCES artifact(hash), review_state TEXT NOT NULL);
CREATE TABLE review_decision(review_id TEXT PRIMARY KEY, subject_hash TEXT NOT NULL, actor_id TEXT NOT NULL, authority_ref TEXT, scope_id TEXT NOT NULL, decision TEXT NOT NULL, evidence_json TEXT NOT NULL, recorded_at TEXT NOT NULL);
CREATE TABLE human_effort(activity_id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES project(project_id), participant_code TEXT NOT NULL, category TEXT NOT NULL, monotonic_start_ns TEXT NOT NULL, monotonic_end_ns TEXT, source_type TEXT NOT NULL, assistance TEXT);
CREATE TRIGGER ledger_no_update BEFORE UPDATE ON ledger BEGIN SELECT RAISE(ABORT,'ledger is append-only'); END;
CREATE TRIGGER ledger_no_delete BEFORE DELETE ON ledger BEGIN SELECT RAISE(ABORT,'ledger is append-only'); END;
-- Trusted retention/export migrations use a separate explicit procedure; no promise of undeletable data.
